column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
call_parentheses = "Always"
quote_style = "AutoPreferSingle"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
